#Spring Cloud Stream Binder配置
spring:
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: localhost:9876
        bindings:
          cluster-out-0:
            producer:
              group: output_0_group
      bindings:
        cluster-out-0:
          destination: cluster

feign:
  sentinel:
    enabled: true

---

spring:
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8088

##Spring Cloud Stream Binder配置：延迟消息
#spring:
#  cloud:
#    stream:
#      rocketmq:
#        binder:
#          name-server: localhost:9876
#        bindings:
#          delayed-out-0:
#            producer:
#              group: output_0_delay_group
#              sync: true #必须设置
#      bindings:
#        cluster-out-0:
#          destination: delay
