server:
  port: 8003

spring:
  application:
    name: integration-service

  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      enabled: true
    config:
      server-addr: 127.0.0.1:8848

feign:
  client:
    config:
      integration-service:
        loggerLevel: FULL

logging:
  level:
    org:
      geekbang:
        projects:
          cs: DEBUG