server:
  port: 8003

spring:
  application:
    name: integration-service
  profiles:
    active: @spring.profiles.active@
  cloud:
    nacos:
      server-addr: @spring.cloud.nacos.discovery.server-addr@
      enabled: true
    config:
      server-addr: 127.0.0.1:8848

feign:
  client:
    config:
      integration-service:
        loggerLevel: FULL
  sentinel:
    enabled: true

logging:
  level:
    org:
      geekbang:
        projects:
          cs: DEBUG

---

spring:
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8088