server:
  port: 8081

spring:
  application:
    name: customer-task

  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      enabled: true
    config:
      server-addr: 127.0.0.1:8848

xxl:
  job:
    accessToken: default_token
    admin:
      addresses: http://localhost:8080/xxl-job-admin
    executor:
      appname: customer-system
      logpath: D:/xxl-job-executor/logs
      logretentiondays: 30

logging:
  level:
    org:
      geekbang:
        projects:
          cs: DEBUG