server:
  port: 9002
    
management:
  endpoints:
    web:
      exposure:
        include: "*"  

spring:
  application:
    name: im-feign

logging:
    level:
      org.geekbang.projects.cs: INFO

      
